language: go

go:
  - tip

env:
  - GOARCH=amd64

install:
  - go get github.com/mattn/go-sqlite3
  - go get github.com/ondrejd/odtimetracker-go-lib
  - go get github.com/ondrejd/odtimetracker-go-cgi/jsonrpc
